// autopackage 

package {
    location: "http://coapp.org/repository/${OutputFilename}";
    feed: "http://coapp.org/repository/packages.atom.xml";
    publisher: "CoApp Project";
}


/*
metadata {
    licenses : {
        Proprietary
    };
    
}
*/

identity[CoApp Project] {
    name : "CoApp Project, Outercurve Foundation";
    email: "coapp@coapp.org";
    website: "http://coapp.org";
}
